/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as LangLlmsDottxtRouteImport } from './routes/$lang/llms[.]txt'
import { Route as LangLlmsFullDottxtRouteImport } from './routes/$lang/llms-full[.]txt'
import { Route as LangDocsChar123Char125DotmdRouteImport } from './routes/$lang/docs/{$}[.]md'
import { Route as LangDocsSplatRouteImport } from './routes/$lang/docs/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLlmsDottxtRoute = LangLlmsDottxtRouteImport.update({
  id: '/$lang/llms.txt',
  path: '/$lang/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLlmsFullDottxtRoute = LangLlmsFullDottxtRouteImport.update({
  id: '/$lang/llms-full.txt',
  path: '/$lang/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LangDocsChar123Char125DotmdRoute =
  LangDocsChar123Char125DotmdRouteImport.update({
    id: '/$lang/docs/{$}.md',
    path: '/$lang/docs/{$}.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const LangDocsSplatRoute = LangDocsSplatRouteImport.update({
  id: '/$lang/docs/$',
  path: '/$lang/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang/llms-full.txt': typeof LangLlmsFullDottxtRoute
  '/$lang/llms.txt': typeof LangLlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
  '/$lang/docs/{$}.md': typeof LangDocsChar123Char125DotmdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/llms-full.txt': typeof LangLlmsFullDottxtRoute
  '/$lang/llms.txt': typeof LangLlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
  '/$lang/docs/{$}.md': typeof LangDocsChar123Char125DotmdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang/llms-full.txt': typeof LangLlmsFullDottxtRoute
  '/$lang/llms.txt': typeof LangLlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
  '/$lang/docs/{$}.md': typeof LangDocsChar123Char125DotmdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang/llms-full.txt'
    | '/$lang/llms.txt'
    | '/api/search'
    | '/$lang/'
    | '/$lang/docs/$'
    | '/$lang/docs/{$}.md'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/llms-full.txt'
    | '/$lang/llms.txt'
    | '/api/search'
    | '/$lang'
    | '/$lang/docs/$'
    | '/$lang/docs/{$}.md'
  id:
    | '__root__'
    | '/'
    | '/$lang/llms-full.txt'
    | '/$lang/llms.txt'
    | '/api/search'
    | '/$lang/'
    | '/$lang/docs/$'
    | '/$lang/docs/{$}.md'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangLlmsFullDottxtRoute: typeof LangLlmsFullDottxtRoute
  LangLlmsDottxtRoute: typeof LangLlmsDottxtRoute
  ApiSearchRoute: typeof ApiSearchRoute
  LangIndexRoute: typeof LangIndexRoute
  LangDocsSplatRoute: typeof LangDocsSplatRoute
  LangDocsChar123Char125DotmdRoute: typeof LangDocsChar123Char125DotmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/$lang'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/llms.txt': {
      id: '/$lang/llms.txt'
      path: '/$lang/llms.txt'
      fullPath: '/$lang/llms.txt'
      preLoaderRoute: typeof LangLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/llms-full.txt': {
      id: '/$lang/llms-full.txt'
      path: '/$lang/llms-full.txt'
      fullPath: '/$lang/llms-full.txt'
      preLoaderRoute: typeof LangLlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/docs/{$}.md': {
      id: '/$lang/docs/{$}.md'
      path: '/$lang/docs/{$}.md'
      fullPath: '/$lang/docs/{$}.md'
      preLoaderRoute: typeof LangDocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/docs/$': {
      id: '/$lang/docs/$'
      path: '/$lang/docs/$'
      fullPath: '/$lang/docs/$'
      preLoaderRoute: typeof LangDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangLlmsFullDottxtRoute: LangLlmsFullDottxtRoute,
  LangLlmsDottxtRoute: LangLlmsDottxtRoute,
  ApiSearchRoute: ApiSearchRoute,
  LangIndexRoute: LangIndexRoute,
  LangDocsSplatRoute: LangDocsSplatRoute,
  LangDocsChar123Char125DotmdRoute: LangDocsChar123Char125DotmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
