//! Server-side TLS material: self-signed cert generation, PEM I/O, and
//! key-permission enforcement. The leaf cert's SHA-256 fingerprint is what
//! clients pin (see `portunus-client/src/pinned_verifier.rs`).
//!
//! Wired into `serve` in T035; until then `dead_code` lints would fire.

#![allow(dead_code)]

use std::path::{Path, PathBuf};

use portunus_core::PortunusError;
use portunus_core::fingerprint;
use rcgen::{
    CertificateParams, DistinguishedName, DnType, KeyPair, PKCS_ECDSA_P256_SHA256, SanType,
};

/// Material loaded (or freshly generated) for the TLS listener.
#[derive(Debug, Clone)]
pub struct ServerTlsMaterial {
    pub cert_pem: String,
    pub key_pem: String,
    /// SHA-256 of the leaf cert DER, lowercase hex (64 chars). What clients pin.
    pub leaf_fingerprint_hex: String,
}

impl ServerTlsMaterial {
    /// Load from disk, or generate fresh material if either file is
    /// missing. When `desired_san` is `Some(host)` and the on-disk pair
    /// is Portunus-autogenerated (a `.portunus-autocert` marker exists),
    /// regenerate if the marker's baked host differs from `host`.
    /// Operator-supplied pairs (no marker) are never modified.
    /// Refuses to start if `key_path` exists with perms broader than 0600.
    pub fn load_or_generate(
        cert_path: &Path,
        key_path: &Path,
        desired_san: Option<&str>,
    ) -> Result<Self, PortunusError> {
        let marker = marker_path(cert_path);
        if cert_path.exists() && key_path.exists() {
            enforce_key_perms(key_path)?;
            let cert_pem = std::fs::read_to_string(cert_path)?;
            let key_pem = std::fs::read_to_string(key_path)?;
            let der = leaf_der_from_pem(&cert_pem)?;
            let loaded = Self {
                leaf_fingerprint_hex: fingerprint::sha256_hex(&der),
                cert_pem,
                key_pem,
            };
            let Some(want) = desired_san else {
                return Ok(loaded);
            };
            if !marker.exists() {
                tracing::warn!(
                    event = "tls.operator_cert_in_use",
                    host = %want,
                    "operator-supplied {} present; ensure its SAN covers {want} \
                     (Portunus will not modify an operator cert)",
                    cert_path.display()
                );
                return Ok(loaded);
            }
            let baked = std::fs::read_to_string(&marker)
                .map(|s| s.trim().to_string())
                .unwrap_or_default();
            if baked == want {
                return Ok(loaded);
            }
            backup_pair(cert_path, key_path);
            let material = generate_self_signed(Some(want))?;
            std::fs::write(cert_path, &material.cert_pem)?;
            write_secret(key_path, material.key_pem.as_bytes())?;
            std::fs::write(&marker, want)?;
            tracing::warn!(
                event = "tls.cert_regenerated",
                host = %want,
                old_fingerprint = %loaded.leaf_fingerprint_hex,
                new_fingerprint = %material.leaf_fingerprint_hex,
                "gRPC cert regenerated for new advertised host {want}; \
                 existing client bundles must be re-issued \
                 (portunus-server enroll-client …)"
            );
            Ok(material)
        } else {
            let material = generate_self_signed(desired_san)?;
            ensure_parent(cert_path)?;
            ensure_parent(key_path)?;
            std::fs::write(cert_path, &material.cert_pem)?;
            write_secret(key_path, material.key_pem.as_bytes())?;
            std::fs::write(&marker, desired_san.unwrap_or(""))?;
            Ok(material)
        }
    }
}

fn ensure_parent(p: &Path) -> std::io::Result<()> {
    if let Some(parent) = p.parent() {
        std::fs::create_dir_all(parent)?;
    }
    Ok(())
}

#[cfg(unix)]
fn write_secret(path: &Path, body: &[u8]) -> std::io::Result<()> {
    use std::io::Write;
    use std::os::unix::fs::OpenOptionsExt;
    let mut f = std::fs::OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .mode(0o600)
        .open(path)?;
    f.write_all(body)?;
    f.sync_all()
}

#[cfg(not(unix))]
fn write_secret(path: &Path, body: &[u8]) -> std::io::Result<()> {
    std::fs::write(path, body)
}

#[cfg(unix)]
fn enforce_key_perms(path: &Path) -> Result<(), PortunusError> {
    use std::os::unix::fs::PermissionsExt;
    let meta = std::fs::metadata(path)?;
    let mode = meta.permissions().mode() & 0o777;
    if mode & 0o077 != 0 {
        return Err(PortunusError::Tls(format!(
            "{} has mode {mode:o}, refuse to start (must be ≤ 0600)",
            path.display()
        )));
    }
    Ok(())
}

#[cfg(not(unix))]
fn enforce_key_perms(_: &Path) -> Result<(), PortunusError> {
    Ok(())
}

fn marker_path(cert_path: &Path) -> PathBuf {
    cert_path.with_file_name(".portunus-autocert")
}

fn push_host_san(sans: &mut Vec<SanType>, host: &str) -> Result<(), PortunusError> {
    if let Ok(ip) = host.parse::<std::net::IpAddr>() {
        sans.push(SanType::IpAddress(ip));
    } else {
        sans.push(SanType::DnsName(host.to_string().try_into().map_err(
            |e| PortunusError::Tls(format!("host '{host}' not valid for SAN: {e}")),
        )?));
    }
    Ok(())
}

fn backup_pair(cert_path: &Path, key_path: &Path) {
    let stamp = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    for p in [cert_path, key_path] {
        let bak = PathBuf::from(format!("{}.portunus.{stamp}.bak", p.display()));
        let _ = std::fs::copy(p, &bak);
    }
}

fn generate_self_signed(extra_host: Option<&str>) -> Result<ServerTlsMaterial, PortunusError> {
    use std::net::{IpAddr, Ipv4Addr, Ipv6Addr};

    let hostname = hostname().unwrap_or_else(|| "portunus-server".to_string());
    let mut params = CertificateParams::default();
    params.not_before = time::OffsetDateTime::now_utc();
    params.not_after = params.not_before + time::Duration::days(365 * 10);
    params.distinguished_name = DistinguishedName::new();
    params
        .distinguished_name
        .push(DnType::CommonName, hostname.clone());
    // SANs: webpki refuses certs with no SAN. Always cover the machine
    // hostname + loopback; additionally cover the advertised host so a
    // remote client verifying against it passes name validation.
    let mut sans = vec![
        SanType::DnsName(
            hostname
                .clone()
                .try_into()
                .map_err(|e| PortunusError::Tls(format!("hostname not valid for SAN: {e}")))?,
        ),
        SanType::DnsName("localhost".try_into().unwrap()),
        SanType::IpAddress(IpAddr::V4(Ipv4Addr::LOCALHOST)),
        SanType::IpAddress(IpAddr::V6(Ipv6Addr::LOCALHOST)),
    ];
    if let Some(h) = extra_host {
        push_host_san(&mut sans, h)?;
    }
    params.subject_alt_names = sans;

    let key_pair = KeyPair::generate_for(&PKCS_ECDSA_P256_SHA256)
        .map_err(|e| PortunusError::Tls(e.to_string()))?;
    let cert = params
        .self_signed(&key_pair)
        .map_err(|e| PortunusError::Tls(e.to_string()))?;
    let cert_pem = cert.pem();
    let key_pem = key_pair.serialize_pem();
    let der = cert.der().to_vec();
    Ok(ServerTlsMaterial {
        leaf_fingerprint_hex: fingerprint::sha256_hex(&der),
        cert_pem,
        key_pem,
    })
}

fn hostname() -> Option<String> {
    std::env::var("HOSTNAME").ok().or_else(|| {
        std::process::Command::new("hostname")
            .output()
            .ok()
            .and_then(|o| {
                let s = String::from_utf8(o.stdout).ok()?;
                let trimmed = s.trim();
                (!trimmed.is_empty()).then(|| trimmed.to_string())
            })
    })
}

fn leaf_der_from_pem(pem: &str) -> Result<Vec<u8>, PortunusError> {
    use base64::Engine as _;
    let mut in_block = false;
    let mut buf = String::new();
    for line in pem.lines() {
        let line = line.trim();
        if line == "-----BEGIN CERTIFICATE-----" {
            in_block = true;
            buf.clear();
            continue;
        }
        if line == "-----END CERTIFICATE-----" {
            return base64::engine::general_purpose::STANDARD
                .decode(buf.trim())
                .map_err(|e| PortunusError::Tls(format!("base64 decode: {e}")));
        }
        if in_block {
            buf.push_str(line);
        }
    }
    Err(PortunusError::Tls("no CERTIFICATE block in PEM".into()))
}

#[allow(dead_code)]
pub fn fingerprint_paths(cert_path: &Path) -> Result<(PathBuf, String), PortunusError> {
    let pem = std::fs::read_to_string(cert_path)?;
    let der = leaf_der_from_pem(&pem)?;
    Ok((cert_path.to_path_buf(), fingerprint::sha256_hex(&der)))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trip_generate_then_load_matches_fingerprint() {
        let dir = tempfile::tempdir().unwrap();
        let cert = dir.path().join("server.crt");
        let key = dir.path().join("server.key");

        let m1 = ServerTlsMaterial::load_or_generate(&cert, &key, None).unwrap();
        // Both files must now exist.
        assert!(cert.exists());
        assert!(key.exists());

        let m2 = ServerTlsMaterial::load_or_generate(&cert, &key, None).unwrap();
        assert_eq!(m1.leaf_fingerprint_hex, m2.leaf_fingerprint_hex);
        assert_eq!(m1.cert_pem, m2.cert_pem);
    }

    #[cfg(unix)]
    #[test]
    fn key_file_is_mode_0600() {
        use std::os::unix::fs::PermissionsExt;
        let dir = tempfile::tempdir().unwrap();
        let cert = dir.path().join("server.crt");
        let key = dir.path().join("server.key");
        ServerTlsMaterial::load_or_generate(&cert, &key, None).unwrap();
        let mode = std::fs::metadata(&key).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode, 0o600, "got mode {mode:o}");
    }

    #[cfg(unix)]
    #[test]
    fn refuses_to_load_with_loose_key_perms() {
        use std::os::unix::fs::PermissionsExt;
        let dir = tempfile::tempdir().unwrap();
        let cert = dir.path().join("server.crt");
        let key = dir.path().join("server.key");
        ServerTlsMaterial::load_or_generate(&cert, &key, None).unwrap();
        // Loosen the permissions.
        let mut perms = std::fs::metadata(&key).unwrap().permissions();
        perms.set_mode(0o640);
        std::fs::set_permissions(&key, perms).unwrap();
        let err = ServerTlsMaterial::load_or_generate(&cert, &key, None).unwrap_err();
        match err {
            PortunusError::Tls(msg) => assert!(msg.contains("mode")),
            other => panic!("expected Tls error, got {other:?}"),
        }
    }

    #[test]
    fn fingerprint_is_64_hex_chars() {
        let dir = tempfile::tempdir().unwrap();
        let m = ServerTlsMaterial::load_or_generate(
            &dir.path().join("c.crt"),
            &dir.path().join("c.key"),
            None,
        )
        .unwrap();
        assert_eq!(m.leaf_fingerprint_hex.len(), 64);
        assert!(
            m.leaf_fingerprint_hex
                .chars()
                .all(|c| c.is_ascii_hexdigit())
        );
    }

    #[test]
    fn generates_with_dns_extra_san() {
        let dir = tempfile::tempdir().unwrap();
        let cert = dir.path().join("server.crt");
        let key = dir.path().join("server.key");
        let m =
            ServerTlsMaterial::load_or_generate(&cert, &key, Some("portunus.example.com")).unwrap();
        assert!(m.cert_pem.contains("BEGIN CERTIFICATE"));
        assert!(dir.path().join(".portunus-autocert").exists());
        assert_eq!(
            std::fs::read_to_string(dir.path().join(".portunus-autocert")).unwrap(),
            "portunus.example.com"
        );
    }

    #[test]
    fn autogen_regenerates_on_host_change() {
        let dir = tempfile::tempdir().unwrap();
        let cert = dir.path().join("server.crt");
        let key = dir.path().join("server.key");
        let a = ServerTlsMaterial::load_or_generate(&cert, &key, Some("a.example.com")).unwrap();
        let b = ServerTlsMaterial::load_or_generate(&cert, &key, Some("b.example.com")).unwrap();
        assert_ne!(a.leaf_fingerprint_hex, b.leaf_fingerprint_hex);
        let baks: Vec<_> = std::fs::read_dir(dir.path())
            .unwrap()
            .filter_map(Result::ok)
            .filter(|e| e.file_name().to_string_lossy().contains(".portunus."))
            .collect();
        assert!(!baks.is_empty(), "expected a .bak backup pair");
    }

    #[test]
    fn autogen_idempotent_same_host() {
        let dir = tempfile::tempdir().unwrap();
        let cert = dir.path().join("server.crt");
        let key = dir.path().join("server.key");
        let a = ServerTlsMaterial::load_or_generate(&cert, &key, Some("x.example.com")).unwrap();
        let b = ServerTlsMaterial::load_or_generate(&cert, &key, Some("x.example.com")).unwrap();
        assert_eq!(a.leaf_fingerprint_hex, b.leaf_fingerprint_hex);
    }

    #[test]
    fn operator_cert_without_marker_never_regenerated() {
        let dir = tempfile::tempdir().unwrap();
        let cert = dir.path().join("server.crt");
        let key = dir.path().join("server.key");
        let orig =
            ServerTlsMaterial::load_or_generate(&cert, &key, Some("old.example.com")).unwrap();
        std::fs::remove_file(dir.path().join(".portunus-autocert")).unwrap();
        let again =
            ServerTlsMaterial::load_or_generate(&cert, &key, Some("new.example.com")).unwrap();
        assert_eq!(orig.leaf_fingerprint_hex, again.leaf_fingerprint_hex);
    }

    #[test]
    fn ip_extra_san_is_accepted() {
        let dir = tempfile::tempdir().unwrap();
        let cert = dir.path().join("server.crt");
        let key = dir.path().join("server.key");
        let m = ServerTlsMaterial::load_or_generate(&cert, &key, Some("203.0.113.7")).unwrap();
        assert!(m.cert_pem.contains("BEGIN CERTIFICATE"));
    }
}
