// Old docs slug -> new docs slug, for 301-redirecting pre-restructure URLs.
// Keys/values are page slugs with no language prefix, no leading slash, no #fragment.
// An empty-string value means the Overview picker at /{lang}/docs.
export const OLD_TO_NEW: Record<string, string> = {
  'getting-started/installation': '',
  'getting-started/architecture': 'overview/architecture',
  'getting-started/performance': 'overview/performance',
  'getting-started/performance-history': 'overview/performance-history',
  'features/tcp-forwarding': 'overview/concepts/tcp-forwarding',
  'features/udp-forwarding': 'overview/concepts/udp-forwarding',
  'features/port-range': 'overview/concepts/port-range',
  'features/dns-targets': 'overview/concepts/dns-targets',
  'features/multi-target-failover': 'overview/concepts/multi-target-failover',
  'features/proxy-protocol': 'overview/concepts/proxy-protocol',
  'features/tls-sni-routing': 'server-client/features/tls-sni-routing',
  'features/rate-limiting': 'server-client/features/rate-limiting',
  'features/rbac': 'server-client/features/rbac',
  'features/web-ui': 'server-client/features/web-ui',
  'features/advertised-endpoint': 'server-client/features/advertised-endpoint',
  'features/sqlite-storage': 'server-client/features/sqlite-storage',
  'configuration/standalone': 'standalone/configuration',
  'configuration/server': 'server-client/configuration/server',
  'configuration/client': 'server-client/configuration/client',
  'cli/installer': 'server-client/cli/installer',
  'cli/portunus-server': 'server-client/cli/portunus-server',
  'cli/portunus-client': 'server-client/cli/portunus-client',
  'cli/walkthrough': 'server-client/cli/walkthrough',
  'api/operator-http': 'server-client/api/operator-http',
  'deployment/systemd': 'server-client/deployment/systemd',
  'deployment/docker': 'server-client/deployment/docker',
  'deployment/railway': 'server-client/deployment/railway',
  'observability/metrics': 'server-client/observability/metrics',
  'observability/audit-log': 'server-client/observability/audit-log',
  'observability/logging': 'server-client/observability/logging',
  'operations/backup-restore': 'server-client/operations/backup-restore',
  'operations/upgrade': 'server-client/operations/upgrade',
  'operations/runbook-traffic-quotas': 'server-client/operations/runbook-traffic-quotas',
  'operations/troubleshooting': 'server-client/operations/troubleshooting',
};
